server:
  port: 2335
spring:
  application:
    name: springboot-shiro
  datasource:
    initial-size: 10
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.29.32.62:3306/haoxy?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: 7d428bc667
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    max-active: 100
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  thymeleaf:
     suffix: .html
     mode: HTML5
     encoding: UTF-8
     content-type: text/html; charset=utf-8
     cache: false

#mybatits配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml